import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: '고립·은둔청년과 가족을 위한 지원 문의 안내', description: '대구청년센터 지원사업 문의처와 전국 청년미래센터 사업의 지역 접수 확인 경로를 안내합니다.', alternates: { canonical: '/research/support' } };
const daeguNotice = 'https://www.daegu.go.kr/index.do?bbsId=BBS_00029&menu_id=00000854&menu_link=%2Ficms%2Fbbs%2FselectBoardArticle.do&nttId=786666';
const nationalNotice = 'https://www.betterfuture.go.kr/front/notificationSpace/cardNewsDetail.do?articleId=476&listLen=9&pageIndex=1&position=S';

export default function SupportGuidePage() {
  return <article className="research-wrap research-section research-detail research-article">
    <header className="research-page-heading"><p className="research-eyebrow">SUPPORT GUIDE · <time dateTime="2026-09-07">2026.09.07 확인</time></p><h1>도움이 필요할 때,<br />어디부터 문의하면 될까요?</h1><p>대구의 청년과 가족이 지원사업을 알아볼 때 사용할 문의처와 확인할 내용을 모았습니다.</p></header>
    <p className="research-article-intro">외출이나 사람을 만나는 일이 어렵거나, 가족으로서 어떻게 도움을 구해야 할지 막막할 수 있습니다. 처음에는 “제가 이용할 수 있는 상담이 있나요?”라고 물어보는 것부터 시작할 수 있습니다. 이 페이지는 문의 경로 안내이며, 실제 신청은 각 사업의 공식 창구에서 진행합니다.</p>
    <section className="research-support-contact"><p className="research-eyebrow">대구 지역 사업 문의</p><h2>대구광역시청년센터 성장지원팀</h2><a className="research-support-phone" href="tel:0534271934">053-427-1934</a><p>사회적 고립청년 지원사업의 현재 모집 프로그램, 가족 상담 가능 여부와 신청 방법을 문의할 수 있습니다.</p><div className="research-hero-links"><a className="research-button" href="tel:0534271934">전화로 문의하기 ↗</a><a href="https://www.dgyouth.kr/board/notice.asp" target="_blank" rel="noopener noreferrer">청년센터 현재 공고 보기 ↗</a></div><p className="research-stat-source">문의처 근거: <a href={daeguNotice} target="_blank" rel="noopener noreferrer">대구시 2026년 2월 10일 공식 공고</a>. 담당 번호의 전화 연결과 현재 잔여 모집 인원은 확인하지 않았습니다.</p></section>
    <section><h2>대구 사업은 청년과 가족의 상담 경로를 안내합니다</h2><p>대구시의 2026년 ‘1:1 심화 심리상담 시즌1’ 공고는 정서·사회적 고립으로 상담이 필요한 <strong>대구 거주 19~39세 청년과 가족</strong>을 대상으로 안내했습니다. 청년과 가족의 신청 절차를 나누어 설명한 공고입니다.</p><p>해당 차수의 사업 기간은 2026년 2월 24일~3월 26일로 이미 지났습니다. 이전 신청서를 그대로 제출하기보다 청년센터의 현재 공고나 위 담당팀을 통해 다음 상담·프로그램의 접수 가능 여부를 확인해 주세요. 가족만 먼저 상담할 수 있는지, 본인의 신청이 필요한지도 함께 물어볼 수 있습니다.</p><p><a href={daeguNotice} target="_blank" rel="noopener noreferrer">대구시 공고의 대상·절차 확인 ↗</a></p></section>
    <section><h2>전국 청년미래센터 사업은 지역 접수부터 확인해 주세요</h2><p>정부의 2026년 7월 21일 안내는 9월부터 청년미래센터를 전국 17개소로 확대하고, <strong>19~34세 고립·은둔청년</strong>에게 상담과 회복 프로그램 등을 제공한다고 설명합니다. 안내된 신청 경로는 청년ON, 주소지 청년미래센터와 읍면동 행정복지센터입니다.</p><aside className="research-note"><h3>대구의 실제 접수 창구는 확인이 필요합니다</h3><p>이 페이지의 확인 범위에서는 대구 청년미래센터의 수행기관과 접수 개시일을 확정하지 못했습니다. <a href="tel:129">보건복지상담센터 129</a> 또는 주소지 행정복지센터에 거주지역의 접수처를 먼저 확인해 주세요. 대구청년센터의 기존 사업과 전국 청년미래센터 사업은 신청 연령과 절차가 다를 수 있습니다.</p></aside><p>함께 안내되는 자기돌봄비 200만 원은 가족돌봄청년을 위한 별도 지원입니다. 고립·은둔청년 모두에게 지급되는 현금 지원으로 이해하지 않도록 사업별 대상을 확인해 주세요.</p><p><a href={nationalNotice} target="_blank" rel="noopener noreferrer">정부의 전국 확대 안내 ↗</a> · <a href="https://www.mohw2030.co.kr/panel.asp" target="_blank" rel="noopener noreferrer">청년ON에서 지역·신청 조건 확인 ↗</a></p></section>
    <section><h2>문의할 때 이렇게 이야기해 볼 수 있습니다</h2><p>아래 문장은 문의를 시작하기 위한 예시입니다. 자세한 사정을 처음부터 모두 설명할 필요는 없습니다.</p><blockquote className="research-support-example">“대구에 사는 청년입니다. 사람을 만나거나 외출하는 일이 어려워요. 지금 신청할 수 있는 상담이 있는지, 어떤 방식으로 시작하는지 알고 싶어요.”</blockquote><blockquote className="research-support-example">“가족으로서 먼저 상담하고 싶어요. 청년 본인은 아직 상담을 망설이고 있는데, 가족이 이용할 수 있는 지원과 필요한 절차를 알려 주세요.”</blockquote><ul className="research-guide-list"><li>지금 접수하는 프로그램의 연령·거주지 조건과 마감일</li><li>전화·온라인·방문 중 가능한 첫 상담 방식</li><li>가족만 먼저 문의하거나 상담할 수 있는지</li><li>필요한 신청서·동의서와 비용, 다음 연락을 받을 방법</li></ul><p>서류와 상담 방식은 프로그램별로 다릅니다. 공고에 적힌 절차와 담당자의 안내를 확인한 뒤 준비해 주세요.</p></section>
    <section><h2>함께 읽으면 좋은 글</h2><Link href="/research/notes/family-first-inquiry">가족이 먼저 문의했을 때, 누구의 이야기를 어떻게 들을까 →</Link></section>
  </article>;
}
